import { execFileSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';
import process from 'node:process';

import { convertBody } from './convert.ts';
import { fetchContent } from './fetch.ts';
import { Mdn } from './mdn.ts';
import { parseFrontmatter } from './parse.ts';
import { releasesFrom } from './release-dates.ts';

/**
 * Imports Firefox's developer release notes from `mdn/content` as MDX.
 *
 * Run with `pnpm run import:release-notes`. Re-runnable: it deletes and
 * rewrites the whole output directory, so pages removed upstream don't linger
 * and the human check is the git diff. Pass `--fresh` to re-fetch the content
 * checkout rather than reuse the cached one.
 *
 * Deliberately noisy on anything it doesn't recognize. An unknown macro or
 * alert type aborts the run naming the file and line, rather than passing the
 * syntax through to produce a page that renders `{{SomeMacro}}` as text.
 */

/**
 * Firefox 60 (2018) is the floor. Below it, every page brings XUL- and
 * add-on-era complexity that no longer applies: all the nested sub-pages, the
 * tree's only image, and `{{Deprecated_Inline}}`/`{{ListSubpages}}`. Older
 * versions link out to MDN instead. The script is re-runnable, so the floor
 * can be lowered later.
 */
const MIN_VERSION = 60;

const OUTPUT_DIR = 'src/content/release-notes';
const CACHE_DIR = path.join('node_modules', '.cache', 'mdn-content');

async function main(): Promise<void> {
  const isFresh = process.argv.includes('--fresh');
  const releases = await releasesFrom(MIN_VERSION, CACHE_DIR, isFresh);
  const years = new Map(releases.map((r) => [r.version, r.year]));

  console.log(
    `Fetching mdn/content${isFresh ? ' (fresh)' : ''}, ${String(releases.length)} versions in scope…`,
  );
  const checkout = fetchContent(CACHE_DIR, isFresh);
  const mdn = new Mdn(checkout.root);
  const sourceDirectory = path.join(checkout.root, 'mozilla/firefox/releases');

  // Rewritten from scratch each run, so upstream deletions propagate.
  rmSync(OUTPUT_DIR, { recursive: true, force: true });
  mkdirSync(OUTPUT_DIR, { recursive: true });

  let written = 0;
  const skipped: string[] = [];

  for (const release of releases) {
    const source = path.join(sourceDirectory, release.version, 'index.md');
    if (!existsSync(source)) {
      skipped.push(release.version);
      continue;
    }

    const relativeSource = `mozilla/firefox/releases/${release.version}/index.md`;
    const { body } = parseFrontmatter(readFileSync(source, 'utf8'));
    const { body: converted, hasNote } = convertBody(body, {
      mdn,
      years,
      file: relativeSource,
    });

    // `releaseDate` is the only key written. MDN's `slug`, `page-type` and
    // `sidebar` describe the page's place in MDN's tree rather than ours, and
    // `title`, `short-title` and the version are all derivable from the entry
    // — see `_release-note.ts` beside the route. Writing a derivable value
    // would only give it a second place to be wrong.
    const frontmatter = ['---', `releaseDate: ${release.date}`, '---'];

    const imports = hasNote
      ? ["import Note from '~/components/Note';", '']
      : [];

    const out = [
      ...frontmatter,
      '',
      `{/* Generated by \`pnpm run import:release-notes\` from mdn/content@${checkout.sha.slice(0, 12)} */}`,
      `{/* Source: files/en-us/${relativeSource} — edit there, not here. */}`,
      '',
      ...imports,
      converted.replace(/^\n+/, ''),
    ].join('\n');

    const directory = path.join(OUTPUT_DIR, release.version);
    mkdirSync(directory, { recursive: true });
    writeFileSync(path.join(directory, 'index.mdx'), `${out.trimEnd()}\n`);
    written += 1;
  }

  if (skipped.length > 0) {
    console.log(`No MDN page for: ${skipped.join(', ')}`);
  }
  console.log(
    `Wrote ${String(written)} notes from mdn/content@${checkout.sha.slice(0, 12)}`,
  );

  // Format what we wrote, so the diff is content rather than formatting noise.
  console.log('Formatting…');
  execFileSync(
    'pnpm',
    ['exec', 'prettier', '--write', '--log-level', 'warn', OUTPUT_DIR],
    {
      stdio: 'inherit',
    },
  );
}

await main();
